### ISSUE TITLE
Why the download speeds are getting slowed down?

### ISSUE THREAD

**Issue by wx69wx** [EverythingSuckz/TG-FileStreamBot#104]
What is the principle of generating direct links? Before the download speed is very fast, but now the download does not move，I can not find the reason.

**Comment by EverythingSuckz** [comment]
Oh, you deployed the instance and it's not fast enough? Are you sure that the bot is configured properly and it's not being used my many users. If it's being used by many users, then I highly encourage you to use the multi - client feature to handle more requests. 

If you have already done everything that I mentioned above and just wanted to know why speeds are slow, then I guess the answer is just **Telegram enforcing more limits for the API** recently. Since this project is open sourced, many users are using it and I'm sure that Telegram Team is totally aware of this and they have been imposing more and more limits (often floodwaits) to reduce the API misuse.

And for the principle part, this project makes use of mtproto API to download the file, but rather than saving the file to the server and sending it to the requested user, this webapp will directly stream data to the end user in real-time without even saving to ths file and ultimately avoid the waiting process.

**Comment by wx69wx** [comment]
thanks for reply^ ,  I only use it by myself.  The reason must be the limit for the API.
